name: fix
description: File a bug report
title: "[fix]: "
labels: ["fix"]
projects: ["/projects/1/views/1"]
assignees:
  - jean079
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: assignee
    attributes:
      label: Assignee
      description: Who should be assigned to this issue?
      options:
        - jean079
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Importance
    attributes:
      label: Importance
      description: How critical is the issue?
      options:
        - critical
        - important
        - normal
      default: 0
    validations:
      required: true
  - type: textarea
    id: User info
    attributes:
      label: User info
      description: provide user info if applicable
      render: shell
