name: Problem Report
description: Report an issue or problem
title: "[Issue]: "
labels: ["issue", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue!
  - type: textarea
    id: problem-statement
    attributes:
      title: Problem Statement
      description: Please describe the problem or issue you encountered.
      placeholder: Describe the problem in detail.
    validations:
      required: true
  - type: textarea
    id: userinfo
    attributes:
      label: User Information
      description: If you'd like to provide your contact information (e.g., name, email address), you can do so here.
      placeholder: Enter your contact information (optional).
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is the problem?
      options:
        - Critical
        - Important
        - Not Urgent
      default: 0
    validations:
      required: true
