name: Maintenance Report
description: Report a maintenance that needs to be done on the project.
labels: ["maintenance"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue!
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Please describe the maintenance that needs to be done.
      placeholder: Describe what needs to be done.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Extra information
      description: If applicable provide screenshot.
      placeholder: Enter Extra information (optional).
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is the problem?
      options:
        - Critical
        - Important
        - Not Urgent
    validations:
      required: true
