name: Send PR Description

on:
  pull_request:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract PR Description
      run: |
        echo "PR Description: ${{ github.event.pull_request.body }}" >> pr_description.txt

    - name: Send Email
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        echo "Sending email..."
        # Replace the following with your email sending code or script.
        # You can use a tool like 'sendmail' or 'mailx' to send an email with the PR description.
        # Example (replace with your own email command):
        echo "PR Description: ${{ github.event.pull_request.body }}" | mail -s "Pull Request Description" $TO_EMAIL

        # Optionally, you can remove the pr_description.txt file after sending the email.
        # rm pr_description.txt
