name: Send PR Description

on:
  pull_request:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract PR Description
      run: |
        echo "PR Description: ${{ github.event.pull_request.body }}" >> pr_description.txt

    - name: Send some mail
      uses: wadeww/send-email-action@master
      with:
        server_address:  ${{ secrets.SMTP_SERVER }}
        port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Workflow finished
        body: Job completed 
        to: jean574@gmail.com
        from: Me



         # - name: Send Email
    #   uses: softprops/action-email@v3
    #   with:
    #     server: ${{ secrets.SMTP_SERVER }}
    #     port: ${{ secrets.SMTP_PORT }}
    #     username: ${{ secrets.SMTP_USERNAME }}
    #     password: ${{ secrets.SMTP_PASSWORD }}
    #     to: ${{ secrets.TO_EMAIL }}
    #     subject: "PR Description"
    #     body: |
    #       $(cat pr_description.txt)