name: Send PR Description

on:
  pull_request:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract PR Description
      run: |
        echo "PR Description: ${{ github.event.pull_request.body }}" >> pr_description.txt

    - name: Install ssmtp
      run: |
        sudo apt-get update
        sudo apt-get install -y ssmtp

    - name: Send Email
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        echo -e "Subject: PR Description\n" > email.txt
        cat pr_description.txt >> email.txt
        echo "" >> email.txt
        echo "Sent from GitHub Actions." >> email.txt
        ssmtp $TO_EMAIL < email.txt
