name: Your Workflow Name

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for any tag pushed
    branches:
      - main

jobs:
  your_job_name:
    if: github.event_name == 'push' && github.ref_type == 'tag' && github.ref == 'refs/tags/v*' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Your Step
        run: echo "Your job is running"
